<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;
// We use them as strings as rel path , no import
// import GreeceDestination from '../../../../public/Images/Greece.png';
// import PragueCastle from '../../../../public/Images/PragueCastle.png';
// import PhuketThaiDestination from '../../../../public/Images/PhuketThailandDestination.png';

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $destinations = [
            [
                'title' => 'Santorini, Greece',
                'subtitle' => 'Cyclades Islands',
                'description' => 'Famous for its dramatic views, stunning sunsets, and white-washed houses with blue domes.',
                'image' => '../../../../public/Images/Greece.png',
                'rating' => 4.9,
                'reviews' => 1243,
                'price' => 2499,
                'is_featured' => true,
                'category' => 'Island',
            ],
            [
                'title' => 'Amalfi Coast, Italy',
                'subtitle' => 'Campania Region',
                'description' => 'A stunning stretch of coastline with colorful cliffside villages overlooking the Tyrrhenian Sea.',
                'image' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 987,
                'price' => 3199,
                'is_featured' => true,
                'category' => 'Coastal',
            ],
            [
                'title' => 'Kyoto, Japan',
                'subtitle' => 'Kansai Region',
                'description' => 'Ancient temples, traditional tea houses, and beautiful cherry blossoms in this cultural capital.',
                'image' => 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'reviews' => 1892,
                'price' => 2899,
                'is_featured' => true,
                'category' => 'Cultural',
            ],
            [
                'title' => 'Bali, Indonesia',
                'subtitle' => 'Lesser Sunda Islands',
                'description' => 'Spiritual retreats, lush rice terraces, and beautiful beaches in this tropical paradise.',
                'image' => 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'reviews' => 2789,
                'price' => 1799,
                'is_featured' => true,
                'category' => 'Tropical',
            ],
            [
                'title' => 'Swiss Alps',
                'subtitle' => 'Switzerland',
                'description' => 'Majestic mountains, crystal clear lakes, and charming alpine villages await in this winter wonderland.',
                'image' => 'https://images.unsplash.com/photo-1523633589114-88eaf4b4f1a8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'reviews' => 1456,
                'price' => 3499,
                'is_featured' => true,
                'category' => 'Mountain',
            ],
            [
                'title' => 'Maldives',
                'subtitle' => 'Indian Ocean',
                'description' => 'Overwater bungalows, crystal clear turquoise waters, and pristine white sand beaches.',
                'image' => 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'reviews' => 2345,
                'price' => 4199,
                'is_featured' => true,
                'category' => 'Luxury',
            ],
            [
                'title' => 'Paris, France',
                'subtitle' => 'Île-de-France',
                'description' => 'The City of Light with iconic landmarks, world-class cuisine, and romantic atmosphere.',
                'image' => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'reviews' => 4123,
                'price' => 2199,
                'is_featured' => false,
                'category' => 'Urban',
            ],
            [
                'title' => 'New York City',
                'subtitle' => 'New York, USA',
                'description' => 'The city that never sleeps with iconic skyscrapers, Broadway shows, and diverse culture.',
                'image' => 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'reviews' => 4567,
                'price' => 2499,
                'is_featured' => false,
                'category' => 'Urban',
            ],
            [
                'title' => 'Sydney, Australia',
                'subtitle' => 'New South Wales',
                'description' => 'Iconic Opera House, beautiful harbor, and stunning beaches in this vibrant coastal city.',
                'image' => 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 2890,
                'price' => 3299,
                'is_featured' => false,
                'category' => 'Coastal',
            ],
            [
                'title' => 'Dubai, UAE',
                'subtitle' => 'United Arab Emirates',
                'description' => 'Futuristic skyscrapers, luxury shopping, and desert adventures in this modern metropolis.',
                'image' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'reviews' => 3123,
                'price' => 2899,
                'is_featured' => false,
                'category' => 'Luxury',
            ],
            [
                'title' => 'Rome, Italy',
                'subtitle' => 'Lazio Region',
                'description' => 'Ancient history, stunning architecture, and delicious cuisine in the Eternal City.',
                'image' => 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 3789,
                'price' => 2399,
                'is_featured' => false,
                'category' => 'Historical',
            ],
            [
                'title' => 'Barcelona, Spain',
                'subtitle' => 'Catalonia',
                'description' => 'Gaudi architecture, vibrant culture, and beautiful Mediterranean beaches.',
                'image' => 'https://images.unsplash.com/photo-1583422409516-2895a77efded?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'reviews' => 2987,
                'price' => 2199,
                'is_featured' => false,
                'category' => 'Cultural',
            ],
            [
                'title' => 'Tokyo, Japan',
                'subtitle' => 'Kanto Region',
                'description' => 'A perfect blend of traditional culture and futuristic innovation in this vibrant metropolis.',
                'image' => 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 3456,
                'price' => 3099,
                'is_featured' => false,
                'category' => 'Urban',
            ],
            [
                'title' => 'Cape Town, South Africa',
                'subtitle' => 'Western Cape',
                'description' => 'Table Mountain, beautiful coastlines, and rich cultural diversity in this stunning city.',
                'image' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 1890,
                'price' => 2599,
                'is_featured' => false,
                'category' => 'Adventure',
            ],
            [
                'title' => 'Rio de Janeiro',
                'subtitle' => 'Brazil',
                'description' => 'Christ the Redeemer, Copacabana beach, and vibrant carnival celebrations.',
                'image' => 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'reviews' => 2345,
                'price' => 2199,
                'is_featured' => false,
                'category' => 'Urban',
            ],
            [
                'title' => 'London, UK',
                'subtitle' => 'England',
                'description' => 'Historic landmarks, world-class museums, and vibrant multicultural atmosphere.',
                'image' => 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'reviews' => 5123,
                'price' => 2399,
                'is_featured' => false,
                'category' => 'Historical',
            ],
            [
                'title' => 'Iceland',
                'subtitle' => 'Nordic Island',
                'description' => 'Northern Lights, geothermal lagoons, waterfalls, and stunning volcanic landscapes.',
                'image' => 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'reviews' => 1678,
                'price' => 3599,
                'is_featured' => false,
                'category' => 'Adventure',
            ],
            [
                'title' => 'Phuket, Thailand',
                'subtitle' => 'Andaman Sea',
                'description' => 'Beautiful beaches, vibrant nightlife, and rich Thai culture in this tropical paradise.',
                'image' => '../../../../public/Images/PhuketThailandDestination.png',
                'rating' => 4.7,
                'reviews' => 2987,
                'price' => 1699,
                'is_featured' => false,
                'category' => 'Tropical',
            ],
            [
                'title' => 'Venice, Italy',
                'subtitle' => 'Veneto Region',
                'description' => 'Romantic canals, historic architecture, and charming gondola rides.',
                'image' => 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 2678,
                'price' => 2899,
                'is_featured' => false,
                'category' => 'Romantic',
            ],
            [
                'title' => 'Marrakech, Morocco',
                'subtitle' => 'Marrakech-Safi',
                'description' => 'Vibrant souks, stunning palaces, and rich cultural heritage in this exotic destination.',
                'image' => 'https://images.unsplash.com/photo-1548013146-72479768bada?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'reviews' => 1890,
                'price' => 1999,
                'is_featured' => false,
                'category' => 'Cultural',
            ],
            [
                'title' => 'Queenstown, New Zealand',
                'subtitle' => 'South Island',
                'description' => 'Adventure capital with stunning landscapes, skiing, and outdoor activities.',
                'image' => 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'reviews' => 1456,
                'price' => 3299,
                'is_featured' => false,
                'category' => 'Adventure',
            ],
            [
                'title' => 'Cancún, Mexico',
                'subtitle' => 'Quintana Roo',
                'description' => 'Beautiful Caribbean beaches, ancient Mayan ruins, and vibrant nightlife.',
                'image' => 'https://images.unsplash.com/photo-1510097467424-192d713fd8b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'reviews' => 2678,
                'price' => 1899,
                'is_featured' => false,
                'category' => 'Beach',
            ],
            [
                'title' => 'Prague, Czech Republic',
                'subtitle' => 'Bohemia',
                'description' => 'Medieval architecture, charming old town, and rich European history.',
                'image' => '../../../../public/Images/PragueCastle.png',
                'rating' => 4.8,
                'reviews' => 2345,
                'price' => 1999,
                'is_featured' => false,
                'category' => 'Historical',
            ],
            [
                'title' => 'Singapore',
                'subtitle' => 'Southeast Asia',
                'description' => 'Modern metropolis with diverse cultures, amazing food, and stunning gardens.',
                'image' => 'https://images.unsplash.com/photo-1531590878845-12627191e687?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 3123,
                'price' => 2599,
                'is_featured' => false,
                'category' => 'Urban',
            ],
            [
                'title' => 'Edinburgh, Scotland',
                'subtitle' => 'Scotland',
                'description' => 'Historic castle, medieval architecture, and rich cultural heritage.',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'reviews' => 1789,
                'price' => 2199,
                'is_featured' => false,
                'category' => 'Historical',
            ],
            [
                'title' => 'Hawaii, USA',
                'subtitle' => 'Pacific Islands',
                'description' => 'Volcanoes, beautiful beaches, and rich Polynesian culture in this tropical paradise.',
                'image' => 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'reviews' => 3456,
                'price' => 3199,
                'is_featured' => false,
                'category' => 'Tropical',
            ],
            [
                'title' => 'Budapest, Hungary',
                'subtitle' => 'Central Europe',
                'description' => 'Thermal baths, stunning architecture, and vibrant nightlife along the Danube.',
                'image' => 'https://images.unsplash.com/photo-1551867633-194f125bddfa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'reviews' => 1678,
                'price' => 1799,
                'is_featured' => false,
                'category' => 'Cultural',
            ],
            [
                'title' => 'Los Angeles, USA',
                'subtitle' => 'California',
                'description' => 'Hollywood, beautiful beaches, and vibrant entertainment scene.',
                'image' => 'https://images.unsplash.com/photo-1515896769750-31548aa180ed?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'reviews' => 3123,
                'price' => 2499,
                'is_featured' => false,
                'category' => 'Urban',
            ],
            [
                'title' => 'Maui, Hawaii',
                'subtitle' => 'Hawaiian Islands',
                'description' => 'Stunning beaches, volcanic landscapes, and world-class snorkeling.',
                'image' => 'https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'reviews' => 2345,
                'price' => 3399,
                'is_featured' => false,
                'category' => 'Beach',
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::create($destination);
        }
    }
}